server{
        listen 80 default_server;
        server_name localhost;
        charset utf-8;
        access_log /var/log/nginx/nginx.log;
        error_log /var/log/nginx/nginx.error.log debug;
        open_file_cache max=200000 
        inactive=20s;
        open_file_cache_valid 30s;
        open_file_cache_min_uses 2;
        open_file_cache_errors on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_requests 100000;
        reset_timedout_connection on;
        client_body_timeout 10;
        send_timeout 2;
        proxy_connect_timeout 900;
        proxy_send_timeout 900; 
        proxy_read_timeout 900; 
        types_hash_max_size 2048;
        client_max_body_size 1024M;
        sendfile on;
        keepalive_timeout 1800;

        location /jskydy-org-view {
                alias /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
        }
        location /{ 
             return 200 "All OK"; 
        }
        location /jskydy-org-view/api/ {
	        proxy_pass http://jskydy-org-api:8089/;
        }
        location /jskydy-org-view/api/v1/tracking {
	        proxy_pass http://eventtrack-front-api.dev-eventtrack:8086/api/v1/tracking;
        }
        location /jskydy-org-view/v2-api/ {
                proxy_pass http://jskydy-org-api:8089/;
        }
        location /jskydy-org-view/ks3/ {
	        proxy_pass http://ks3-cn-shanghai-2.nhdc.cn/;
        }

}

